env:
    browser: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: es6
    sourceType: module
ignorePatterns: ["dist"]
plugins:
    - "@typescript-eslint"
rules:
    "@typescript-eslint/no-explicit-any": "off"
